# Generated by Django 6.0.5 on 2026-05-22 03:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot', models.CharField(choices=[('hero_card', 'Hero Section — Main Card'), ('auth_ring_1', 'Auth Layout — Ring 1 (large)'), ('auth_ring_2', 'Auth Layout — Ring 2 (small)')], help_text='Each slot holds one active image.', max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='hero/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Image',
                'verbose_name_plural': 'Hero Images',
            },
        ),
    ]
