# Generated by Django 6.0.5 on 2026-05-21 22:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Standard Shipping', max_length=100)),
                ('fee_usd', models.DecimalField(decimal_places=2, default=12.0, max_digits=8)),
                ('estimated_days_min', models.PositiveIntegerField(default=8)),
                ('estimated_days_max', models.PositiveIntegerField(default=15)),
                ('description', models.CharField(default='Shipped from China via express courier', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Shipping Configuration',
                'verbose_name_plural': 'Shipping Configurations',
            },
        ),
    ]
